language: minimal

git:
  depth: false
  autocrlf: input # Prevents git to try to be smart with line endings

os:
  - linux
  - osx
  - windows

dist: focal

arch:
  - amd64
  - arm64

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - JDK="adopt@1.11"
  matrix:
    - JDK="adopt@1.11"
    - JDK="adopt@1.8"
    - JDK="adopt@1.14"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt-openj9@1.8"
    - JDK="adopt-openj9@1.14"

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

install:
  - true

script:
  - ./gradlew check