language: java

git:
  depth: false
  autocrlf: input # Prevents git to try to be smart with line endings

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

install:
  - true

script:
  - ./gradlew check