if: repo != head_repo AND (tag IS blank OR tag =~ /\d+(\.\d+)*/)

_reference_os: &reference_os
  linux
_reference_arch: &reference_arch
  amd64
_reference_jdk: &reference_jdk
  JDK="adopt@1.11"
_reference_machine: &reference_machine
  arch: *reference_arch
  os: *reference_os
  env: *reference_jdk
_workspace_name: &workspace_name
                   compiled_env
_import_workspace: &import_workspace
  workspaces:
    use: *workspace_name

language: minimal

git:
  depth: false
  autocrlf: input # Prevents git to try to be smart with line endings

os:
  - *reference_os
  - osx
  - windows

dist: focal

arch:
  - *reference_arch
  - arm64

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM=dumb
    - secure: "MdbOr5CuW6NQLx8GCffLuyOrh8j/e1uxs/V2imyqJgH9ZllzHk7+ZuTgcTznCrMX0GYW/ohuLD1yXQ263bjhSdsPxHUPsSMEfvc2K2ECgKkmYAI0xOpIXV4gA/Tqof+qkUrTOje6i5eabcoUWH1W2HNDkbSYHeomexJOQy6cEmXpSNP41IcQtwJZwMotu44YTISYLQKBg+e2ysv+mc5hoGbJvTK//t0xl2CCnjZY87V9gqk+RDxbK4npwfMtqLhpMwULm6NTURI9KZmFWm24MVRbv3OdUcPcN9Cr9H5+TQ6I4AP48XMFg9klhMAqnme5/oXfZnZPedd4dcwB7XtHswdonIa9BPnNWx43sW13IM5puUmX9aEljsTv+XUHKD7lbO9D+zUMVdz1V786GK+p633ulGah9tsqT4HKl8oY3ayc4sbIkFd4F1KX/qL/FG2W3Onpy96GzDU6AJ5+eD32UrpV83GEGcDsOXY2e9JRsV9mNE45OgOWD8h0L08+YEf80ye8dGQPrCbOSsvywKyKGcomUdtvYoOvnkrsLhoSwwcVpgs3yu7wonD5C23quV0o0kXsNtNxi92k5+zadj87SKacxHMyyuNuVAi2Ggy4jge8ul8nBoZmogBv+cpahVZEwEwHgQw7pMzN9CMrYjEktw3GRHXB6nGLT/gYA6u/cCM="


  matrix:
    - *reference_jdk
    - JDK="adopt@1.8"
    - JDK="adopt@1.14"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt-openj9@1.8"
    - JDK="adopt-openj9@1.14"

_repo_slug: &repo_slug
  nlasagni/deleteme-lss

stages:
  - Compile
  - Kotlin Style Check
  - Complete Check
  - name: test
    if: 'commit_message !~ /\[\s*skip(?: |-|\.)test\s*\].*/'
  - name: Delivery
    if: repo = nlasagni/deleteme-lss

jobs:
  exclude:
    - arch: arm64
      env: JDK="adopt-openj9@1.8"
    - arch: arm64
      env: JDK="adopt-openj9@1.14"
    - <<: *reference_machine
      stage: test
  include:
    - <<: *reference_machine
      stage: Compile
      script:
        - ./gradlew compileKotlin --parallel
      workspaces:
        create:
          name: *workspace_name
          paths:
            - "$TRAVIS_BUILD_DIR"
            - "$HOME/.gradle"
    - <<: *reference_machine
      stage: Kotlin Style Check
      <<: *import_workspace
      script:
        - ./gradlew detekt ktlintCheck --parallel
    - <<: *reference_machine
      stage: Complete Check
      <<: *import_workspace
      script:
        - travis_retry ./gradlew check
    - stage: Delivery
      before_script:
        - openssl aes-256-cbc -K $encrypted_f778b2e1574b_key -iv $encrypted_f778b2e1574b_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - travis_retry ./gradlew publishMavenCentralPublicationToMavenRepository
      after_success:
        - ./gradlew publishPlugins -Pgradle.publish.key=$PLUGIN_PORTAL_KEY -Pgradle.publish.secret=$PLUGIN_PORTAL_SECRET
      before_deploy:
        - ./gradlew generateVersionFile
        - export VERSION=$(cat build/version)
        - git tag -a $VERSION -m "Version $VERSION"
      deploy:
        provider: releases # Deploys on GitHub Releases
        file: build/libs/*.jar # Files to deploy
        edge: true # opt in to the new deploy API
        on: # filter
          all_branches: true
          # tags: true # deploy only tags

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

install:
  - "true"

script:
  - travis_retry ./gradlew test